### ISSUE TITLE
Bluetooth steering delay

### ISSUE THREAD

**Issue by LukasBaecker** [zauberzeug/field_friend#147] opened 2024-07-30 13:06 UTC
When steering the robot using the mobile app and connected to the robot via Bluetooth we observed a massive delay (with robot U4). The delay is especially with higher driving speeds very dangerous.

**Comment by rodja** [comment] 2024-07-30 16:35
It's not happening all the time. How can we reproduce this behaviour? Does it stop when you tap again on the screen?

**Comment by LukasBaecker** [comment] 2024-07-31 07:23
> It's not happening all the time. How can we reproduce this behaviour? Does it stop when you tap again on the screen?

Yes, tapping on the screen seems to stop the robot when it moves with delay.

**Comment by rodja** [comment] 2024-09-05 04:48
With the Zauberzeug app version 1.5.8 we added a workaround by sending the stop command multiple times. I'll close this issue because the Field Friend problem is fixed.

**Closed by rodja** 2024-09-05 04:48 UTC
