### ISSUE TITLE
Robot drives a bit faster after pressing/releasing the e-stop

### ISSUE THREAD

**Issue by rodja** [zauberzeug/field_friend#86] opened 2024-06-24 15:00 UTC
With u6 we observed a very strange behaviour. Reproduction:

- jack the robot up
- start a long straight line driving automation
- press e-stop
- release e-stop
- robot tracks are turning faster than before

Why?

**Comment by pascalzauberzeug** [comment] 2024-08-27 08:10
We couldnt reproduce the issue, I will close it now

**Closed by pascalzauberzeug** 2024-08-27 08:10 UTC
Labels: bug
