### ISSUE TITLE
Navigation._proceed not awaited

### ISSUE THREAD

**Issue by Johannes-Thiel** [zauberzeug/field_friend#108] opened 2024-07-03 12:17 UTC
on the main branch, when running a straight line navigation with the weeding screw the Error 
```

rosys_1       | /app/field_friend/automations/navigation/navigation.py:44: RuntimeWarning: coroutine 'Navigation._proceed' was never awaited
rosys_1       |   await rosys.automation.parallelize(
rosys_1       | RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
pops up, when the robot is looking for new plants but does not find any. The Robot will not continue to drive.
When the ._proceed is awaited the robot will dirve.

**Comment by rodja** [comment] 2024-07-07 14:20
I have seen this warning sometimes but can not reproduce it reliable (in simulation or test). 

> The Robot will not continue to drive.

I don't think this is related to this warning but some  other issue.

> When the ._proceed is awaited the robot will drive.

The coroutines should not be awaited individually when passed into the `parallelize` construct. As the docu write:

> This class allows to combine multiple coroutines into one that can be passed to the `automator <https://rosys.io/reference/rosys/automation/#rosys.automation.Automator>`__ to run them in parallel.

The whole purpose is to run coroutines in parallel so awaiting one individually will make it execute alone. In this case "driving forward" without stopping for weeds.

**Comment by pascalzauberzeug** [comment] 2024-07-19 10:57
I will close this Issue because `parallelize` was removed in https://github.com/zauberzeug/field_friend/pull/102.

**Closed by pascalzauberzeug** 2024-07-19 10:57 UTC
Labels: bug
